name: Generate 3D Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 產生 3D 城市立體網格圖
      - name: Generate 3D Contribution Grid
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Richard-yq

      # 提交 3D 城市圖到 main 分支
      - name: Commit & Push 3D Grid SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Update 3D Contribution Grid" || exit 0
          git pull --rebase origin main
          git push
